# Generated by Django 3.0.8 on 2020-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=20)),
                ('population', models.CharField(max_length=50)),
            ],
        ),
    ]
