# Generated by Django 3.0.8 on 2020-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('age', models.CharField(max_length=2)),
                ('mobile_number', models.CharField(max_length=11)),
                ('std_class', models.CharField(max_length=10)),
            ],
        ),
    ]
