# Generated by Django 3.0.8 on 2020-07-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Khulna', max_length=50),
            preserve_default=False,
        ),
    ]
